services:
  - type: web
    name: kabuto-ai
    env: python
    plan: free
    buildCommand: ""
    startCommand: python kabuto_ai/bot.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_API_TOKEN
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: PORT
        sync: false